### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by mimenda2** [Swastika-IO/Swastika-IO-Core#56]
Hi!
I've downloaded the code directly and using git clone with the same result. (step 1)

I've follow the steps:
2. dotnet restore: works ok
3. dotnet build: fails because can not find the CORE projects: swastika and swastika.Identity

Any idea?

regards,
David C.

**Comment by Smilefounder** [comment]
Hi @mimenda2 , thanks for trying.

Please clone the Identity project from the following https://github.com/Swastika-IO/Swastika-IO-Identity and build again. 

Or you can ref to Nuget https://www.nuget.org/packages/Swastika.Identity/

As we are still working on Identity features, we haven't pushed the latest version to Nuget yet.

Please try again and let me know if you still facing any issues.

Regards.

**Comment by mimenda2** [comment]
Hi Smilefounder,

I download the  Identity project from  https://github.com/Swastika-IO/Swastika-IO-Identity and the other core project from https://github.com/Swastika-IO/Swastika-IO-Heart

Now all the code compile ok

I run the app, using the Swastika.Cms.Web.Mvc as start project 

App fails trying to connect to sql server database.
I have this connection string in the appsetting.json file:
"CmsConnection": "Server=115.77.190.113,4444;Database=starceramic_new;UID=sa;Pwd=k{+X$f=7K5@#TJsH;MultipleActiveResultSets=true",

regards,

**Comment by nhathoang989** [comment]
Hi @mimenda2 

Please pull code and update the connection string 
  "CmsConnection": null 

Then run again and you will see the screen for input your connection string to init the Cms.

Sorry for the inconviniences,

Regards,
Hoang
