### ISSUE TITLE
The Project Name

### ISSUE THREAD

**Issue by battistone** [Swastika-IO/Swastika-IO-Core#57]
I'm aware that swastikas are a symbol of good fortune in eastern Asia, but in Europe and the Americas, Swastikas have an extremely negative connotation. They're associated with genocide and mass murder, due to the Nazis.

Now, the maintainer can name this project whatever he feels, but: if I were to use this project for my professional needs, my clients would think that I have poor judgment. Will the name be changed? I couldn't use this CMS otherwise.

**Comment by Smilefounder** [comment]
Hello @battistone , appreciated that you're interested in our CMS. You can follow this project https://github.com/Halcyon-Core/Halcyon-Core in case if you don't want to use "Swastika" name. As we are still in development, we not able to update Halcyon in real-time yet. But it will be perfect the same as Swastika (just the name is different). 

Hope we have more feedback and review from you during using our CMS! Cheers!
